### ISSUE TITLE
Problem on installation 

### ISSUE THREAD

**Issue by hliuci** [JBjoernskov/Ifc2Graph#2]
Hi @JBjoernskov  , thanks for developing this library. I tried to install it but I think there is a installation problem. When I typed in` pip install git+https://github.com/JBjoernskov/Ifc2Graph`, the error showed as below, but actually I have ifcopenshell installed. Do you know how can we fix it? Thanks!

Output:
```
Collecting git+https://github.com/JBjoernskov/Ifc2Graph
  Cloning https://github.com/JBjoernskov/Ifc2Graph to /tmp/pip-req-build-lbj_xmh1
  Running command git clone --filter=blob:none --quiet https://github.com/JBjoernskov/Ifc2Graph /tmp/pip-req-build-lbj_xmh1
  Resolved https://github.com/JBjoernskov/Ifc2Graph to commit c49038f31f52b25dd7a8d922c74d87a3fa5fa3a4
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of ifc2graph to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement python-ifcopenshell (from ifc2graph) (from versions: none)
ERROR: No matching distribution found for python-ifcopenshell
```

**Comment by hliuci** [comment]
This problem has been solved by cloning the project locally and removing the requirements for `python` version and `python-ifcopenshell` library.

**Comment by JBjoernskov** [comment]
Hi @hliuci, thanks for reporting this issue.
It appears they changed the naming of the package to **ifcopenshell** from **python-ifcopenshell**.
This is fixed in https://github.com/JBjoernskov/Ifc2Graph/commit/872622b6b147a86028047991e3e65c803732b3c3.
